# Generated by Django 4.2.3 on 2023-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('corporateName', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('abstract', models.CharField(max_length=200, verbose_name='Resumo')),
                ('categoria', models.CharField(choices=[('Moda', 'Moda'), ('Alimentos', 'Alimentos'), ('Rede Social', 'Rede Social'), ('Educação', 'Educação'), ('Saúde', 'Saúde'), ('Financeiro', 'Financeiro'), ('Entretenimento', 'Entretenimento')], max_length=100)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Score')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
