# Generated by Django 4.2.3 on 2023-07-31 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vazou_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=120, unique=True)),
                ('subtitle', models.TextField(max_length=200, unique=True)),
                ('text', models.TextField(max_length=3000)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'noticia',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='abstract',
            field=models.TextField(max_length=300, verbose_name='Resumo'),
        ),
    ]
