# Generated by Django 4.2.3 on 2023-07-31 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vazou_app', '0002_noticia_alter_empresa_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, unique=True, verbose_name='Título da denúncia')),
                ('name_company', models.CharField(max_length=50, verbose_name='Nome da empresa')),
                ('text', models.TextField(max_length=3000, verbose_name='Texto')),
            ],
            options={
                'db_table': 'denuncia',
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última edição'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitle',
            field=models.TextField(max_length=200, unique=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.TextField(max_length=120, unique=True, verbose_name='Título'),
        ),
    ]
