# Generated by Django 4.2.3 on 2023-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazou_app', '0003_denuncia_alter_noticia_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título da denúncia'),
        ),
    ]
