# Generated by Django 4.2.3 on 2023-08-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazou_app', '0005_denuncia_datetime_noticia_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='perfil_image',
            field=models.ImageField(default='', upload_to='Empresa/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fst_image',
            field=models.ImageField(default='', upload_to='Noticia/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='snd_image',
            field=models.ImageField(default='', upload_to='Noticia/'),
        ),
    ]
