# Generated by Django 4.2.3 on 2023-08-22 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vazou_app', '0006_denuncia_status_empresa_perfil_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data e hora'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data e hora'),
        ),
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, verbose_name='Nome')),
                ('lastName', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('adress', models.CharField(max_length=200, verbose_name='endereco')),
                ('startDate', models.DateField(verbose_name='data de inicio')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Endereço de email')),
                ('is_senior', models.BooleanField(default=False)),
                ('authenticated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analista',
            },
        ),
    ]
