# Generated by Django 4.2.3 on 2023-08-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vazou_app', '0007_alter_acao_datetime_alter_denuncia_datetime_analista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_empresa', to='vazou_app.empresa'),
        ),
    ]
