# Generated by Django 4.2.3 on 2023-08-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazou_app', '0008_alter_noticia_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria',
            field=models.CharField(choices=[('Moda', 'Moda'), ('Alimentos', 'Alimentos'), ('Rede Social', 'Rede Social'), ('Educação', 'Educação'), ('Saúde', 'Saúde'), ('Financeiro', 'Financeiro'), ('Entretenimento', 'Entretenimento'), ('Governo', 'Governo'), ('Finanças', 'Finanças'), ('Tecnologia', 'Tecnologia'), ('Transporte', 'Transporte'), ('Varejo', 'Varejo')], max_length=100),
        ),
    ]
