# Generated by Django 4.2.3 on 2023-08-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vazou_app', '0009_alter_empresa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='abstract',
            field=models.TextField(max_length=400, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='edit_date',
            field=models.DateTimeField(null=True, verbose_name='Última edição'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
    ]
